function noise_est2_callback(h_obj, event)
    global output
    global noisemask
    global window
    global raw_noise_std
    global dn_asnr
    
    data = squeeze(output);
    [snr dn_asnr noise_avg dn_noise_std noneed] = noise_est1(data, 1, noisemask);        

    p_noise_cal_result = [0.33 0.40 0.1 0.03]; 

    % noise values
noise_label= uicontrol('Parent', window,...
        'Style', 'text',...
        'FontSize',12,...
        'Units', 'normalized',...
        'String', ['Post-DN > Noise level (std): ' num2str(dn_noise_std, '%.3f')], ...
        'Position', [0.02 0.05 0.3 0.03]); 
    hold on;
    
gain_label= uicontrol('Parent', window,...
        'Style', 'text',...
        'FontSize',14,...
        'Units', 'normalized',...
        'String', ['>> Noise reduction by ' num2str(raw_noise_std/dn_noise_std, '%.1f') '-fold'], ...
        'Position', [0.05 0.01 0.3 0.03]); 
   
end
