% Interactive denoising
close all
clearvars

addpath(genpath('./data'));
addpath(genpath('./Imagescn'));
addpath(genpath('./callbackfun'));

%% initialize
give_positions
load('../data/invivo_hp13c_EPI.mat');
global met_dyn
met_dyn = hp13c;

% Create the window for GUI
global window;
window = figure('Name', 'GL-HOSVD Denoising',...
                'DockControl', 'off',...
                'Units', 'Pixels',...
                'Position', p_window);
            
% Create axes for raw images    
global loc_rawdata;
loc_rawdata = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_raw, 'XTick', [], 'YTick', []);
            
% Create axes for DN images    
global loc_DNdata;
loc_DNdata = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_DN,'XTick', [], 'YTick', []);            

% Create axes for raw auc
global loc_rawdata_auc;
loc_rawdata_auc = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_raw_auc);

% Create axes for dynamic traces
global loc_dyn_traces;
loc_dyn_traces = axes('Parent', window,...
                'Units', 'normalized',...
                'Position', p_ax_dyn_traces,'NextPlot','replacechildren');
                    
%% Origianl Images
raw_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',14,...
                'Units', 'normalized',...
                'String', '<Data>', ...
                'Position', [0.1 0.52 0.3 0.03]);

global met_num;
met_num = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '2',...
                    'Position', p_met_num,  'Callback', @display_callback);
met_num_label = uicontrol('Parent', window,... 
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Metabolite #:',...
                    'Position', p_met_num_label); 
                
global display_slice;
display_slice = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '7',...
                    'Position', p_display_slice, ...
                    'Callback',   @display_callback);
display_slice_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', ['Display slice # (max ' num2str(size(met_dyn,3)) '):'],...
                    'Position', p_display_slice_label); 

global scale_factor;
scale_factor = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '2',...
                    'Position', p_scale_factor, 'Callback', @display_callback);
scale_factor_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Scale factor:',...
                    'Position', p_scale_factor_label);  
                
% read data and plot fid and ft
montage_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',14,...
                    'Units', 'normalized',...
                    'String', 'Pre-denoising',...
                    'Position', [0.19 0.96 0.12 0.03]);
plot_data = uicontrol('Parent', window,...
                    'Style', 'pushbutton',...
                    'String', 'Display Data',...
                    'FontSize', 12,...
                    'Units', 'normalized',...
                    'Position', p_rd_data,...
                    'Callback', @display_callback);

%% noise estimation block
noise_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',14,...
                'Units', 'normalized',...
                'String', '<Noise estimation>', ...
                'Position', [0.1 0.13 0.3 0.03]);
            
rnoise_label= uicontrol('Parent', window,...
            'Style', 'pushbutton',...
            'FontSize',12,...
            'Units', 'normalized',...
            'String', 'Calculate noise level', ...
            'Position', p_noise_cal, ...
            'Callback', @noise_est1_callback); 

%% Denoising parameters
parameter_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',14,...
                'Units', 'normalized',...
                'String', '<Denoising parameters>', ...
                'Position', [0.1 0.355 0.3 0.03]);
matrix_size_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',12,...
                'Units', 'normalized',...
                'String', ['- Matrix size: ' num2str(size(met_dyn,2)) ' x ' , num2str(size(met_dyn,1))], ...
                'Position', [0.02 0.315 0.15 0.03]); 

global patch_size;
patch_size = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '5',...
                    'Position', p_patch_size, 'Callback',@denoise_callback); 
patch_size_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '- Patch size:',...
                    'Position', p_patch_size_label); 
                
global window_size;
window_size = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12, ...
                    'Units', 'normalized',...
                    'String', '6', ...
                    'Position', p_window_size, 'Callback',@denoise_callback); 
window_size_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '- Search window size:',...
                    'Position', p_window_size_label); 
global step_size;
step_size = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12, ...
                    'Units', 'normalized',...
                    'String', '2', ...
                    'Position', p_step_size, 'Callback', @denoise_callback); 
step_size_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '- Step size:',...
                    'Position', p_step_size_label); 

global klocal;
klocal = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12, ...
                    'Units', 'normalized',...
                    'String', '0.8', ...
                    'Position', p_klocal,'Callback',@denoise_callback); 
klocal_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', ['- k_local:'], ...
                    'Position', p_klocal_label); 
                
global kglobal;
kglobal = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12, ...
                    'Units', 'normalized',...
                    'String', '0.4', ...
                    'Position', p_kglobal, 'Callback',@denoise_callback); 
kglobal_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', ['- k_global:'], ...
                    'Position', p_kglobal_label);

%% Denoising
montage_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',14,...
                'Units', 'normalized',...
                'String', 'Post-denoising',...
                'Position', [0.7 0.96 0.12 0.03]);
denoise_data = uicontrol('Parent', window,...
                'Style', 'pushbutton',...
                'String', 'Denoise Data',...
                'FontSize', 12,...
                'Units', 'normalized',...
                'Position', p_do_denoise,...
                'Callback', @denoise_callback); 

%% Dynamic traces
trace_label = uicontrol('Parent', window,...
                'Style', 'text',...
                'FontSize',14,...
                'Units', 'normalized',...
                'String', '<Signal traces>', ...
                'Position', [0.6 0.52 0.3 0.03]);
            
plot_auc = uicontrol('Parent', window,...
        'Style', 'pushbutton',...
        'String', 'Display AUC',...
        'FontSize', 12,...
        'Units', 'normalized',...
        'Position', p_rd_auc,...
        'Callback', @ display_auc_callback);

global x_cord;
x_cord = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '5',...
                    'Position', p_x_cord,'Callback', @display_dyn_callback);
x_cord_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'X:',...
                    'Position', p_x_cord_label);  
global y_cord;
y_cord = uicontrol('Parent', window,...
                    'Style', 'edit',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', '12',...
                    'Position', p_y_cord, 'Callback',  @display_dyn_callback);
y_cord_label = uicontrol('Parent', window,...
                    'Style', 'text',...
                    'FontSize',12,...
                    'Units', 'normalized',...
                    'String', 'Y:',...
                    'Position', p_y_cord_label);   
plot_dyn = uicontrol('Parent', window,...
        'Style', 'pushbutton',...
        'String', 'Display traces',...
        'FontSize', 12,...
        'Units', 'normalized',...
        'Position', p_rd_dyn,...
        'Callback',  @display_dyn_callback);

